# Generated by Django 4.2.8 on 2023-12-15 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('scheduled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestCompletion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quest.quest')),
            ],
        ),
        migrations.CreateModel(
            name='QuestSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repeat_year', models.CharField(default='*', max_length=10)),
                ('repeat_month', models.CharField(default='*', max_length=10)),
                ('repeat_day', models.CharField(default='*', max_length=10)),
                ('repeat_week', models.CharField(default='*', max_length=10)),
                ('repeat_weekday', models.CharField(default='*', max_length=10)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='quest_schedule', to='quest.quest')),
                ('create_time', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
